const dispatch = d3.dispatch("start", "pause", "change", "save", "changeInput", "changeWeightFilter");
let btnTrain = null;
let mapObjects = {};
let mapAreaObjects = {};
let currentModel = null;
const lstmWeightTypes = ["(click to toggle)", "input gate", "forget gate", "cell state", "output gate"];
const lstmWeightTypeDisplay = [0, 0, 0, 1];
const weightTypeDisplay = [1, 1];
let isTraining = false;
let trainLosses;
let testLosses;
let reviewMode = false;
//Draw color scales
const colorBarW = 100;
const colorBarH = 10;
const heatmapH = 100;
const maxLineWeightOpacity = 1.0;
const minLineWeightOpacity = 0.0;
let predictedVariable;
let dataItemName = "Data Instances";
let features;
let selectedFeatures;
let defaultModelIndex = 1;
const trainTestLossColorScheme = ["#a0a0a0", "#f5008c", "#0877bd"];//Used for train tess loss graph.
const testOutputColorScheme = ["#f5008c", "#6a8759", "#f5008c", "#0877bd"];//Used for the test output color scheme
const outputColorScheme = ["#a8aaab", "#6a8759", "#0877bd"];//Used for training output and also immediate layer training output
let trainingProcess = [];
let noOfEpochs = 30;
let noOfBatches = 39;
let minDataVal = null;
let maxDataVal = null;
let networkHeight = null;
let neuronHeight = 122+50-15;
let trainingWeightWidthRatio = 129.125 / 200;//3 / 8;
let neuronShowingHeatmap = false;
let isOutlierGlobal = [];
let neuronData = {unordered: {}, mse: {}, correlation: {}, weights: {}};
let originalNeurons = {};
let originalTrainingWeights = null;
let originalWeights = null;
let hiddenStates = {};
let hiddenSimilarity = {};
let shapValuesMap = {}, shapValuesArray = [];
let cachedMapObjects = {};
let isStateObservationGlobal = [];

let trainIdState = ['Alabama',
    'Alabama',
    'Alabama',
    'Alabama',
    'Alabama',
    'Alabama',
    'Alabama',
    'Alabama',
    'Alabama',
    'Alaska',
    'Alaska',
    'Alaska',
    'Alaska',
    'Alaska',
    'Alaska',
    'Alaska',
    'Alaska',
    'Alaska',
    'Arizona',
    'Arizona',
    'Arizona',
    'Arizona',
    'Arizona',
    'Arizona',
    'Arizona',
    'Arizona',
    'Arizona',
    'Arkansas',
    'Arkansas',
    'Arkansas',
    'Arkansas',
    'Arkansas',
    'Arkansas',
    'Arkansas',
    'Arkansas',
    'Arkansas',
    'California',
    'California',
    'California',
    'California',
    'California',
    'California',
    'California',
    'California',
    'California',
    'Colorado',
    'Colorado',
    'Colorado',
    'Colorado',
    'Colorado',
    'Colorado',
    'Colorado',
    'Colorado',
    'Colorado',
    'Connecticut',
    'Connecticut',
    'Connecticut',
    'Connecticut',
    'Connecticut',
    'Connecticut',
    'Connecticut',
    'Connecticut',
    'Connecticut',
    'Delaware',
    'Delaware',
    'Delaware',
    'Delaware',
    'Delaware',
    'Delaware',
    'Delaware',
    'Delaware',
    'Delaware',
    'Florida',
    'Florida',
    'Florida',
    'Florida',
    'Florida',
    'Florida',
    'Florida',
    'Florida',
    'Florida',
    'Georgia',
    'Georgia',
    'Georgia',
    'Georgia',
    'Georgia',
    'Georgia',
    'Georgia',
    'Georgia',
    'Georgia',
    'Hawaii',
    'Hawaii',
    'Hawaii',
    'Hawaii',
    'Hawaii',
    'Hawaii',
    'Hawaii',
    'Hawaii',
    'Hawaii',
    'Idaho',
    'Idaho',
    'Idaho',
    'Idaho',
    'Idaho',
    'Idaho',
    'Idaho',
    'Idaho',
    'Idaho',
    'Illinois',
    'Illinois',
    'Illinois',
    'Illinois',
    'Illinois',
    'Illinois',
    'Illinois',
    'Illinois',
    'Illinois',
    'Indiana',
    'Indiana',
    'Indiana',
    'Indiana',
    'Indiana',
    'Indiana',
    'Indiana',
    'Indiana',
    'Indiana',
    'Iowa',
    'Iowa',
    'Iowa',
    'Iowa',
    'Iowa',
    'Iowa',
    'Iowa',
    'Iowa',
    'Iowa',
    'Kansas',
    'Kansas',
    'Kansas',
    'Kansas',
    'Kansas',
    'Kansas',
    'Kansas',
    'Kansas',
    'Kansas',
    'Kentucky',
    'Kentucky',
    'Kentucky',
    'Kentucky',
    'Kentucky',
    'Kentucky',
    'Kentucky',
    'Kentucky',
    'Kentucky',
    'Louisiana',
    'Louisiana',
    'Louisiana',
    'Louisiana',
    'Louisiana',
    'Louisiana',
    'Louisiana',
    'Louisiana',
    'Louisiana',
    'Maine',
    'Maine',
    'Maine',
    'Maine',
    'Maine',
    'Maine',
    'Maine',
    'Maine',
    'Maine',
    'Maryland',
    'Maryland',
    'Maryland',
    'Maryland',
    'Maryland',
    'Maryland',
    'Maryland',
    'Maryland',
    'Maryland',
    'Massachusetts',
    'Massachusetts',
    'Massachusetts',
    'Massachusetts',
    'Massachusetts',
    'Massachusetts',
    'Massachusetts',
    'Massachusetts',
    'Massachusetts',
    'Michigan',
    'Michigan',
    'Michigan',
    'Michigan',
    'Michigan',
    'Michigan',
    'Michigan',
    'Michigan',
    'Michigan',
    'Minnesota',
    'Minnesota',
    'Minnesota',
    'Minnesota',
    'Minnesota',
    'Minnesota',
    'Minnesota',
    'Minnesota',
    'Minnesota',
    'Mississippi',
    'Mississippi',
    'Mississippi',
    'Mississippi',
    'Mississippi',
    'Mississippi',
    'Mississippi',
    'Mississippi',
    'Mississippi',
    'Missouri',
    'Missouri',
    'Missouri',
    'Missouri',
    'Missouri',
    'Missouri',
    'Missouri',
    'Missouri',
    'Missouri',
    'Montana',
    'Montana',
    'Montana',
    'Montana',
    'Montana',
    'Montana',
    'Montana',
    'Montana',
    'Montana',
    'Nebraska',
    'Nebraska',
    'Nebraska',
    'Nebraska',
    'Nebraska',
    'Nebraska',
    'Nebraska',
    'Nebraska',
    'Nebraska',
    'Nevada',
    'Nevada',
    'Nevada',
    'Nevada',
    'Nevada',
    'Nevada',
    'Nevada',
    'Nevada',
    'Nevada',
    'New_Hampshire',
    'New_Hampshire',
    'New_Hampshire',
    'New_Hampshire',
    'New_Hampshire',
    'New_Hampshire',
    'New_Hampshire',
    'New_Hampshire',
    'New_Hampshire',
    'New_Jersey',
    'New_Jersey',
    'New_Jersey',
    'New_Jersey',
    'New_Jersey',
    'New_Jersey',
    'New_Jersey',
    'New_Jersey',
    'New_Jersey',
    'New_Mexico',
    'New_Mexico',
    'New_Mexico',
    'New_Mexico',
    'New_Mexico',
    'New_Mexico',
    'New_Mexico',
    'New_Mexico',
    'New_Mexico',
    'New_York',
    'New_York',
    'New_York',
    'New_York',
    'New_York',
    'New_York',
    'New_York',
    'New_York',
    'New_York',
    'North_Carolina',
    'North_Carolina',
    'North_Carolina',
    'North_Carolina',
    'North_Carolina',
    'North_Carolina',
    'North_Carolina',
    'North_Carolina',
    'North_Carolina',
    'North_Dakota',
    'North_Dakota',
    'North_Dakota',
    'North_Dakota',
    'North_Dakota',
    'North_Dakota',
    'North_Dakota',
    'North_Dakota',
    'North_Dakota',
    'Ohio',
    'Ohio',
    'Ohio',
    'Ohio',
    'Ohio',
    'Ohio',
    'Ohio',
    'Ohio',
    'Ohio',
    'Oklahoma',
    'Oklahoma',
    'Oklahoma',
    'Oklahoma',
    'Oklahoma',
    'Oklahoma',
    'Oklahoma',
    'Oklahoma',
    'Oklahoma',
    'Oregon',
    'Oregon',
    'Oregon',
    'Oregon',
    'Oregon',
    'Oregon',
    'Oregon',
    'Oregon',
    'Oregon',
    'Pennsylvania',
    'Pennsylvania',
    'Pennsylvania',
    'Pennsylvania',
    'Pennsylvania',
    'Pennsylvania',
    'Pennsylvania',
    'Pennsylvania',
    'Pennsylvania',
    'Rhode_Island',
    'Rhode_Island',
    'Rhode_Island',
    'Rhode_Island',
    'Rhode_Island',
    'Rhode_Island',
    'Rhode_Island',
    'Rhode_Island',
    'Rhode_Island',
    'South_Carolina',
    'South_Carolina',
    'South_Carolina',
    'South_Carolina',
    'South_Carolina',
    'South_Carolina',
    'South_Carolina',
    'South_Carolina',
    'South_Carolina',
    'South_Dakota',
    'South_Dakota',
    'South_Dakota',
    'South_Dakota',
    'South_Dakota',
    'South_Dakota',
    'South_Dakota',
    'South_Dakota',
    'South_Dakota',
    'Tennessee',
    'Tennessee',
    'Tennessee',
    'Tennessee',
    'Tennessee',
    'Tennessee',
    'Tennessee',
    'Tennessee',
    'Tennessee',
    'Texas',
    'Texas',
    'Texas',
    'Texas',
    'Texas',
    'Texas',
    'Texas',
    'Texas',
    'Texas',
    'Utah',
    'Utah',
    'Utah',
    'Utah',
    'Utah',
    'Utah',
    'Utah',
    'Utah',
    'Utah',
    'Vermont',
    'Vermont',
    'Vermont',
    'Vermont',
    'Vermont',
    'Vermont',
    'Vermont',
    'Vermont',
    'Vermont',
    'Virginia',
    'Virginia',
    'Virginia',
    'Virginia',
    'Virginia',
    'Virginia',
    'Virginia',
    'Virginia',
    'Virginia',
    'Washington',
    'Washington',
    'Washington',
    'Washington',
    'Washington',
    'Washington',
    'Washington',
    'Washington',
    'Washington',
    'West_Virginia',
    'West_Virginia',
    'West_Virginia',
    'West_Virginia',
    'West_Virginia',
    'West_Virginia',
    'West_Virginia',
    'West_Virginia',
    'West_Virginia',
    'Wisconsin',
    'Wisconsin',
    'Wisconsin',
    'Wisconsin',
    'Wisconsin',
    'Wisconsin',
    'Wisconsin',
    'Wisconsin',
    'Wisconsin',
    'Wyoming',
    'Wyoming',
    'Wyoming',
    'Wyoming',
    'Wyoming',
    'Wyoming',
    'Wyoming',
    'Wyoming',
    'Wyoming'];

let testIdState = ['Alabama',
    'Alaska',
    'Arizona',
    'Arkansas',
    'California',
    'Colorado',
    'Connecticut',
    'Delaware',
    'Florida',
    'Georgia',
    'Hawaii',
    'Idaho',
    'Illinois',
    'Indiana',
    'Iowa',
    'Kansas',
    'Kentucky',
    'Louisiana',
    'Maine',
    'Maryland',
    'Massachusetts',
    'Michigan',
    'Minnesota',
    'Mississippi',
    'Missouri',
    'Montana',
    'Nebraska',
    'Nevada',
    'New_Hampshire',
    'New_Jersey',
    'New_Mexico',
    'New_York',
    'North_Carolina',
    'North_Dakota',
    'Ohio',
    'Oklahoma',
    'Oregon',
    'Pennsylvania',
    'Rhode_Island',
    'South_Carolina',
    'South_Dakota',
    'Tennessee',
    'Texas',
    'Utah',
    'Vermont',
    'Virginia',
    'Washington',
    'West_Virginia',
    'Wisconsin',
    'Wyoming'];

document.addEventListener('DOMContentLoaded', function () {
    var elems = document.querySelectorAll('.sidenav');
    var instances = M.Sidenav.init(elems, options);
});
document.addEventListener('DOMContentLoaded', function () {
    var elems = document.querySelectorAll('select');
    var instances = M.FormSelect.init(elems, options);
});

$(document).ready(function () {
    $('.sidenav').sidenav();
    $('select').formSelect();
});

function rearrangeCharts(container, newOrder) {
    let wrapper = $(container),
        items = wrapper.children('div');

    wrapper.empty();
    wrapper.append($.map(newOrder, function (v) {
        return items[v]
    }));
}

// function exportData() {
//     let X_train_outlier = [];
//     let X_train_not_outlier = [];
//     let y_train_outlier = [];
//     let y_train_not_outlier = [];
//
//     isOutlierGlobal.forEach(function (d, i) {
//         if (d) {
//             X_train_outlier.push(X_train[i]);
//             y_train_outlier.push(y_train[i]);
//         } else {
//             X_train_not_outlier.push(X_train[i]);
//             y_train_not_outlier.push(y_train[i]);
//         }
//     });
//
//     // download(JSON.stringify(X_train_outlier), 'X_train_outlier.json', 'text/plain')
//     download(JSON.stringify(X_train_not_outlier), 'X_train_not_outlier.json', 'text/plain')
//     // download(JSON.stringify(y_train_outlier), 'y_train_outlier.json', 'text/plain')
//     download(JSON.stringify(y_train_not_outlier), 'y_train_not_outlier.json', 'text/plain')
// }

